[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "generative-agents"
authors = [
    {name = "Alexander Gruhl", email = "gruhl.alexander@gmail.com"},
]
description = "A simulation framework for generative agents."
readme = "README.md"
requires-python = ">=3.12"
keywords = ["generative agents", "llm", "sim"]
license = {text = "MIT"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
   "llama-cpp-python[server]",
    "pathfinding==1.0.4",
    "python-socketio==5.8.0",
    "aiohttp",
    "pydantic",
    "qdrant-client",
    "jupyterlab==4.0.7",
    "ipykernel==6.25.2",
    "instructor",
    "openai",
    "haystack-ai",
    "qdrant-haystack",
    "llama-cpp-haystack",
    "langfuse-haystack",
    "sentence-transformers",
    "colorama",
    "groq",
    "langgraph",
    "langfuse",
    "gevent",
    "loguru",
    "langchain",
    "langchain-groq",
    "langchain-community",
    "python-dotenv",
    "tqdm",
    "langchain-huggingface"
]
dynamic = ["version"]

[tool.setuptools.dynamic]
version = {attr = "generative_agents.version"}